name: Deploy Frontend to GitHub Pages

on:
  push:
    branches:
      - main # Confirme se esta é a branch principal do seu repositório (geralmente main ou master)
    paths:
      - 'frontend/**' # Isso faz o deploy APENAS se algo mudar dentro da pasta 'frontend/'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Use a versão do Node.js que você usa localmente

      - name: Install dependencies (Frontend)
        run: npm install # Se você usa yarn, mude para: yarn install
        working-directory: ./frontend

      - name: Build Frontend Web
        run: npx expo export --platform web
        working-directory: ./frontend

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./frontend/dist # Caminho para a pasta que contém o build web, gerada no passo anterior

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4